version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: service_request
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9001:9001
    depends_on:
      - postgres
